[build]
  command = "pnpm install --frozen-lockfile && pnpm run build --shamefully-hoist --store=node_modules/.pnpm-store --store-dir=node_modules/.pnpm-store"
  environment = { PNPM_VERSION = "8.15.7" }